import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white">
        <nav className="flex h-[70px] p-4 bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white">
          <span className="text-3xl font-bold">NextAuth</span>
          <span className="flex gap-2 font-semibold ml-auto">
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </span>
        </nav>
        {children}
      </body>
    </html>
  );
}
